# Generated by Django 4.1.5 on 2023-01-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
